version: "3"
services:
  app:
    container_name: rss_aggregator
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    container_name: rss_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5431:5432'
    volumes:
      - db:/var/lib/postgres/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: rss_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  api:
  db: